#! /bin/sh

# Starts programs
$HOME/.local/bin/startup

# Variables {{{

borderWidth=1
# For the no gaps mode
# borderGap=-$borderWidth
borderGap=8

backgroundAlt="#373b41"
blue="#81a2be"

# }}}

# Monitors {{{

# Spread desktops amongs monitors
bspc monitor -d I II III IV V VI VII VIII IX X

# }}}

# Borders & gaps {{{

bspc config border_width $borderWidth
bspc config window_gap $borderGap
for side in top right bottom left ; do
    # To have the borders on the edges of the screen
	# bspc config ${side}_padding $borderWidth

    # Removes the borders on the edges of the screen
	bspc config ${side}_padding 0
done

# }}}

# Windows {{{

# Split in half
bspc config split_ratio 0.5

# Color of the border of an unfocused window.
bspc config normal_border_color $backgroundAlt

# Color of the border of a focused window of an unfocused monitr.
bspc config active_border_color $blue

# Color of the border of a focused window of a focused monitor.
bspc config focused_border_color $blue

# Color of the node --presel-{dir,ratio} message feedback area.
bspc config presel_feedback_color $backgroundAlt

# }}}

# Layouts {{{

# Monocle {{{

# Use the monocle layout when there is only one tiled window
bspc config single_monocle true

# Removes border in monocle layout
bspc config borderless_monocle true

# No gaps in monocle layout
bspc config gapless_monocle true

# }}}

# }}}

# Rules {{{

bspc rule -a *:VimWiki desktop='^10' locked=true follow=true
bspc rule -a qutebrowser desktop='^2' follow=true

# }}}

# vim: fdm=marker
